### ISSUE TITLE
Jupyter Notebook

### ISSUE THREAD

**Issue by jensenity** [ronald-smith-angel/owl-data-sanitizer#4]
I downloaded `pip install owl-sanitizer-data-quality` with my bootstrapfile and here's the pip freeze of it,
<img width="194" alt="Screenshot 2020-12-01 at 3 49 22 PM" src="https://user-images.githubusercontent.com/39326969/100706703-c9733080-33ec-11eb-892d-fe1f7e4dc6e2.png">

When I'm in my jupyter notebook, I don't seem to be able to import the library.
<img width="802" alt="Screenshot 2020-12-01 at 3 51 29 PM" src="https://user-images.githubusercontent.com/39326969/100706878-1a832480-33ed-11eb-9dd9-98bcbadb9678.png">

How do I solve this? How can use this on my jupyter notebook as i select two different dataframes on my notebook?

**Comment by jrinvictus** [comment]
were you able to solve this, i am having the same issue.
